kind: pipeline
name: build
type: kubernetes

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    repo: registry.lan/krichy/haproxy
    registry: registry.lan
    insecure: true
    auto_tag: true

  privileged: true
  volumes:
  - name: docker
    path: /var/lib/docker

volumes:
- name: docker
  temp: {}

